spring:
    application:
        exchange: product.events.fanout.exchange
        queue: event.stream
        terminal: product.axon.terminal
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        rest:
            #base-path: api/v1
logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.soagrowers: TRACE
    file: ./build/logs/query-side-server.log
